### ISSUE TITLE
Allow to customize the remapping alias

### ISSUE THREAD

**Issue by beeb** [mario-eth/soldeer#106]
It would be nice if the remappings could be customized, for example to not add the `@` symbol at the beginning of the alias  (matter of preference) and not include the version number (to keep the same import paths when upgrading the package).

Maybe something like this in the config file:

```toml
[remappings]
enabled = true
prepend_at = false
include_version = false
```

Which would give:

```
// remappings.txt
forge-std=dependencies/forge-std-1.9.1
```
