### ISSUE TITLE
soldeer install hangs and doesn’t log anything

### ISSUE THREAD

**Issue by jirutka** [mario-eth/soldeer#241]
### I have checked the following:

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I have checked that the bug is reproducible with the latest version of Soldeer.

### Soldeer Version

soldeer 0.5.2

### What Happened?

`forge soldeer install` on CI sometimes (but quite often) hangs for minutes until it fails with an error, or the job timeouts.

```sh
$ forge soldeer install
T  🦌 Soldeer Install 🦌
|
*  Done reading config
|  
*  Done reading lockfile
|
# After several minutes...
—  An error occurred during install
Error: Failed to run soldeer error during install operation: error during dependency installation: error downloading dependency: error decoding response body
```

The main problem is that **it doesn’t log anything**, even with `-vvvvv`, so we have no idea what’s going on and troubleshooting is nearly impossible.

### Expected Behavior

Running `forge soldeer install` with `--verbose` should print what exactly it’s doing (and not just a fancy progress bar).

### Configuration

```toml
**foundry.toml**:


[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
auto_detect_solc = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.0.2/",
]

[profile.soldeer]
remappings_generate = false
remappings_regenerate = false
remappings_version = false
remappings_prefix = ""
recursive_deps = true

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"
forge-std = "1.9.2"
cyfrin-foundry-devops = "0.2.2"
solady = "0.0.259"


**gitlab-ci.yml**:

```yaml
build:
  stage: build
  image: ghcr.io/foundry-rs/foundry:latest
  before_script:
    - forge soldeer install
  script:
    - forge build
```
```
