### ISSUE TITLE
Automatically add `dependencies` under `libs` in foundry config

### ISSUE THREAD

**Issue by mario-eth** [mario-eth/soldeer#46]
Currently, you have to the `dependency` directory under the `libs` config in foundry to be recognized automatically.
Would be awesome to be added automatically if not presetn.

E.g.
```toml
[profile.default]
auto_detect_solc = false 
bytecode_hash = "none" 
evm_version = "paris" # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
fuzz = {runs = 1_000} 
gas_reports = ["*"] 
libs = ["dependencies"]  <=== This needs to be added automatically
optimizer = true 
optimizer_runs = 10_000 
out = "out" 
script = "script" 
solc = "0.8.23" 
src = "src" 
test = "test" 

```
